# Generated by Django 3.0.4 on 2020-03-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_labpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpost',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1),
        ),
        migrations.AddField(
            model_name='labpost',
            name='stream',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CV', 'CV'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('LLB', 'LLB'), ('LLM', 'LLM'), ('B-ARCH', 'B-ARCH'), ('BBA-HEM', 'BBA-HEM'), ('B-DES', 'B-DES')], default='CSE', max_length=30),
        ),
        migrations.AddField(
            model_name='labpost',
            name='subject',
            field=models.CharField(default='abcd', max_length=100),
        ),
        migrations.AlterField(
            model_name='labpost',
            name='description',
            field=models.TextField(default=' ', max_length=200),
        ),
    ]
