# Generated by Django 3.0.4 on 2020-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20200323_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpost',
            name='description',
            field=models.TextField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='labpost',
            name='postbody',
            field=models.TextField(blank=True, default=' '),
            preserve_default=False,
        ),
    ]
