# Generated by Django 3.0.4 on 2020-03-24 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0007_auto_20200323_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('stream', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CV', 'CV'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('LLB', 'LLB'), ('LLM', 'LLM'), ('B-ARCH', 'B-ARCH'), ('BBA-HEM', 'BBA-HEM'), ('B-DES', 'B-DES')], default='CSE', max_length=30)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('file1', models.FileField(blank=True, null=True, upload_to='filepost/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='filepost/')),
                ('file3', models.FileField(blank=True, null=True, upload_to='filepost/')),
                ('file4', models.FileField(blank=True, null=True, upload_to='filepost/')),
                ('file5', models.FileField(blank=True, null=True, upload_to='filepost/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
